### ISSUE TITLE
Getting 404 error on private instance?

### ISSUE THREAD

**Issue by paulakfleck** [mathix420/notion-charts#13]
Hello! First of all, thank you for creating this awesome feature.

I've just deployed my Vercel here - https://dashboard-notion.vercel.app/

But whenever I paste a URL from a database, I get 404 errors. What should I be doing?
![image](https://user-images.githubusercontent.com/5883100/113181430-23172a80-9228-11eb-8454-577c38f076f2.png)

Thank you in advance!

**Comment by mathix420** [comment]
Hi!
Glad you like this project ☺️

I need some precision to better understand the issue, is the database link you're using on your deployment working with [charts.notion.ninja](https://charts.notion.ninja)?

**Comment by mathix420** [comment]
If your database is private make it public just the time to test on my deployment.

**Comment by paulakfleck** [comment]
Hey, thanks for replying! [Here's my list public](https://www.notion.so/pfleck/418e88b39eab4ef8abd6c683177f7e87?v=572f7e4510644f5f8da1af24422be182). It only works on the multi-charts version. On the first one, I see `{"error":"404 Not Found: No status found in the response."}`

**Comment by mathix420** [comment]
Hello, No problem! :smile: 

I see the issue now!
(PS: I made an update to clarify my error messages as this one was from notion-charts and not third party :sweat_smile: )

But anyway, your issue is occuring beacause you're trying to use the `classical` version of notion-charts to display something that isn't a TODO chart.

I know the first version was not really flexible, but since I'm developping the `multicharts` version you will be able to do whatever you want with it!

Just deploy my project with this link (or if you know how to do it manually, deploy notion-charts from the multicharts branch)

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/git/external?repository-url=https%3A%2F%2Fgithub.com%2Fmathix420%2Fnotion-charts%2Ftree%2Fmulticharts&env=TOKEN_V2&envDescription=Notion%20session%20cookie&envLink=https%3A%2F%2Fgithub.com%2Fmathix420%2Fnotion-charts%2Fblob%2Fmaster%2Fdocs%2Fnotion-token.md)

Hope it helps!

**Comment by paulakfleck** [comment]
Got it, thanks a lot Math!! :D

**Comment by mathix420** [comment]
My name is Arnaud, but you're welcome! :smile: 
Great! I will mention you on a MR if I needs some help, thanks!
